"""Count source lines in public default-branch archives; never execute repo code."""
import concurrent.futures
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse

CLOC_URL = 'https://raw.githubusercontent.com/AlDanial/cloc/v2.06/cloc'
CLOC_SHA = 'ed9fbdd081a2ceb933ea490b3c1cfacc87d3898ae2650d0d6756439695a836c8'
EXCLUDED = set('venv .venv env .env node_modules vendor vendors third_party third-party site-packages dist build out .next .nuxt .output coverage .git .cache __pycache__ .ipynb_checkpoints generated target Pods .build'.lower().split())
EXTENSIONS = set('.ts .tsx .js .jsx .mjs .cjs .py .go .css .scss .sass .less .html .htm .vue .svelte .sql .rs .java .c .h .cpp .hpp .cc .cs .swift .kt .kts .rb .php .sh .bash .zsh .r .R .lua .ex .exs .erl .scala .dart .pl .pm .sas .ipynb'.lower().split())

def eligible(path):
    parts = pathlib.PurePosixPath(path).parts
    return (not any(p.lower() in EXCLUDED for p in parts)
            and pathlib.PurePosixPath(path).suffix.lower() in EXTENSIONS
            and not re.search(r'(\.min\.|\.bundle\.|\.generated\.|\.g\.cs$|\.pb\.go$|\.d\.ts$)', path.lower()))

def notebook_source(raw):
    book = json.loads(raw)
    lang = book.get('metadata', {}).get('language_info', {}).get('name', 'python').lower()
    ext = {'python': '.py', 'r': '.r', 'julia': '.jl', 'javascript': '.js', 'typescript': '.ts'}.get(lang)
    if not ext:
        raise ValueError('Unsupported notebook language: ' + lang)
    cells = []
    for cell in book.get('cells', []):
        if cell.get('cell_type') == 'code':
            source = cell.get('source', [])
            cells.append(''.join(source) if isinstance(source, list) else source)
    return '\n\n'.join(cells), ext

def download(url, destination):
    subprocess.run(['curl', '--fail', '--location', '--silent', '--show-error', '--retry', '2', '--max-time', '240', url, '-o', str(destination)], check=True)

def count_repo(repo, cloc):
    with tempfile.TemporaryDirectory(prefix='profile-source-') as directory:
        root = pathlib.Path(directory)
        archive = root / 'repo.tar.gz'
        branch = urllib.parse.quote(repo['default_branch'], safe='')
        download(f"https://codeload.github.com/{repo['full_name']}/tar.gz/refs/heads/{branch}", archive)
        sources = root / 'source'
        sources.mkdir()
        index = 0
        with tarfile.open(archive, 'r:gz') as tar:
            for member in tar:
                path = '/'.join(pathlib.PurePosixPath(member.name).parts[1:])
                if not member.isfile() or not eligible(path):
                    continue
                raw = tar.extractfile(member).read()
                ext = pathlib.PurePosixPath(path).suffix.lower()
                if ext == '.ipynb':
                    source, ext = notebook_source(raw)
                    raw = source.encode()
                # Avoid generated sources bearing standard generator headers.
                if re.search(rb'(?i)(auto[- ]generated|generated by|code generated).*?(do not edit|generator)|(?i:do not edit).*?(?i:generated)', raw[:2048]):
                    continue
                # Numbered filenames prevent archive path traversal and symlink writes.
                (sources / f'{index}{ext}').write_bytes(raw)
                index += 1
        if not index:
            return repo['full_name'], {}
        result = subprocess.run(['perl', str(cloc), '--json', '--quiet', '--skip-uniqueness', '--timeout=0', '--max-file-size=100', str(sources)], check=True, capture_output=True, text=True)
        report = json.loads(result.stdout)
        if report.get('errors'):
            raise ValueError('cloc errors: ' + repo['full_name'])
        totals = {}
        for lang, values in report.items():
            if lang in ('header', 'SUM'):
                continue
            lang = {'JSX': 'JavaScript', 'TypeScript JSX': 'TypeScript'}.get(lang, lang)
            totals[lang] = totals.get(lang, 0) + values['code']
        print('Counted ' + repo['full_name'], file=sys.stderr)
        return repo['full_name'], totals

def main():
    repos = json.load(sys.stdin)
    with tempfile.TemporaryDirectory(prefix='profile-cloc-') as directory:
        cloc = pathlib.Path(directory) / 'cloc'
        download(CLOC_URL, cloc)
        if hashlib.sha256(cloc.read_bytes()).hexdigest() != CLOC_SHA:
            raise ValueError('cloc checksum mismatch')
        with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
            results = dict(pool.map(lambda repo: count_repo(repo, cloc), repos))
    totals = {}
    for languages in results.values():
        for lang, lines in languages.items():
            totals[lang] = totals.get(lang, 0) + lines
    print(json.dumps({'totals': totals, 'repositories': results}))

if __name__ == '__main__':
    if '--test' in sys.argv:
        assert eligible('src/app.tsx')
        assert not eligible('foo/venv/lib/code.py')
        assert not eligible('node_modules/pkg/app.js')
        assert not eligible('dist/app.js')
        assert not eligible('app.min.js')
        source, ext = notebook_source(json.dumps({'cells': [{'cell_type': 'markdown', 'source': ['ignored']}, {'cell_type': 'code', 'source': ['print(1)'], 'outputs': ['ignored']}]}))
        assert (source, ext) == ('print(1)', '.py')
        print('Line counter tests passed')
    else:
        main()
